// Deploys the playtest intake Worker (docs/automatic-playtest-collection.md#owner-setup), from the "Deploy playtest
// Worker" workflow or a terminal. Idempotent: run it again to update or repair.
//
//   node worker/scripts/deploy.mjs              find or create the D1 database, apply migrations, deploy, set the
//                                               IMPORT_TOKEN secret, check /api/v1/health. A paused intake stays paused
//   node worker/scripts/deploy.mjs --pause      the same, with INTAKE_PAUSED = "true" (the emergency stop)
//   node worker/scripts/deploy.mjs --resume     the same, with INTAKE_PAUSED = "false"
//   node worker/scripts/deploy.mjs --dry-run    bundle and check the configuration only: no account needed
//
// Needs (except --dry-run), as environment variables, never in a file:
//   CLOUDFLARE_API_TOKEN     an API token allowed to edit Workers Scripts and D1 (docs: "Create the API token")
//   CLOUDFLARE_ACCOUNT_ID    the account's id (public, but kept with the token)
//   PLAYTEST_IMPORT_TOKEN    the import token (at least 32 characters), the same as the GitHub secret of that name
// Optional: PLAYTEST_ALLOWED_ORIGINS (default: https://aceszhenwei.github.io).
// Writes worker/.wrangler.deploy.toml (wrangler.toml with the database id filled in; ignored by git).
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const wrangler = 'wrangler@4.140.0'; // Pinned: a reviewed version, never "latest"
const here = path.dirname(fileURLToPath(import.meta.url));
const workerDir = path.join(here, '..');
const template = path.join(workerDir, 'wrangler.toml');
const generated = path.join(workerDir, '.wrangler.deploy.toml');
const databaseName = 'whitechapel-playtests';
const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const summary = [];

function fail(message) {
	console.error(`\n✖ ${message}`);
	if (process.env.GITHUB_STEP_SUMMARY) fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, `## Deploy playtest Worker\n\n❌ ${message}\n`);
	process.exit(1);
}

function run(argv, { input, capture = true } = {}) {
	// wrangler through npx; its output is shown unless captured. Secrets go through stdin or the environment only
	const result = spawnSync('npx', ['--yes', wrangler, ...argv], { cwd: workerDir, input, encoding: 'utf8',
		stdio: [input === undefined ? 'inherit' : 'pipe', capture ? 'pipe' : 'inherit', capture ? 'pipe' : 'inherit'],
		env: Object.assign({}, process.env, { CI: 'true', WRANGLER_SEND_METRICS: 'false' }) });
	if (result.error) fail(`could not run wrangler: ${result.error.message}`);
	return { code: result.status, out: (result.stdout || '') + (result.stderr || '') };
}

function configure({ databaseId, paused, origins }) {
	let text = fs.readFileSync(template, 'utf8');
	text = text.replace('database_id = "filled-in-by-deploy-script"', `database_id = "${databaseId}"`);
	text = text.replace(/^INTAKE_PAUSED = "(true|false)"$/m, `INTAKE_PAUSED = "${paused ? 'true' : 'false'}"`);
	if (origins) text = text.replace(/^ALLOWED_ORIGINS = ".*"$/m, `ALLOWED_ORIGINS = "${origins}"`);
	fs.writeFileSync(generated, '# Generated by worker/scripts/deploy.mjs from wrangler.toml: do not edit or commit\n' + text);
}

if (dryRun) {
	configure({ databaseId: '00000000-0000-0000-0000-000000000000', paused: false });
	const r = run(['deploy', '--dry-run', '--config', generated, '--outdir', path.join(workerDir, '.wrangler', 'dry-run')], { capture: false });
	if (r.code !== 0) fail('wrangler could not bundle the Worker with this configuration');
	console.log('\n✔ The Worker bundles and its configuration is valid (nothing was deployed).');
	process.exit(0);
}

const missing = ['CLOUDFLARE_API_TOKEN', 'CLOUDFLARE_ACCOUNT_ID', 'PLAYTEST_IMPORT_TOKEN'].filter((k) => !process.env[k]);
if (missing.length) fail(`missing ${missing.join(', ')}: add ${missing.length === 1 ? 'it' : 'them'} as GitHub repository secrets (docs/automatic-playtest-collection.md#owner-setup)`);
if (process.env.PLAYTEST_IMPORT_TOKEN.length < 32) fail('PLAYTEST_IMPORT_TOKEN must be at least 32 characters long');
if (!/^[0-9a-f]{32}$/.test(process.env.CLOUDFLARE_ACCOUNT_ID.trim())) fail('CLOUDFLARE_ACCOUNT_ID should be the 32-character account id from the Cloudflare dashboard');
const origins = process.env.PLAYTEST_ALLOWED_ORIGINS || '';
if (origins && !/^https?:\/\/[A-Za-z0-9.:-]+(,https?:\/\/[A-Za-z0-9.:-]+)*$/.test(origins)) fail('PLAYTEST_ALLOWED_ORIGINS must be origins such as https://name.github.io, comma-separated');

// 1. The D1 database: found by name, or created
function findDatabase() {
	const r = run(['d1', 'list', '--json']);
	if (r.code !== 0) fail(`could not list D1 databases. Check that CLOUDFLARE_API_TOKEN may read and edit D1, and CLOUDFLARE_ACCOUNT_ID.\n${r.out.slice(-800)}`);
	const start = r.out.indexOf('[');
	let list;
	try { list = JSON.parse(r.out.slice(start)); } catch (error) { fail(`unexpected output from wrangler d1 list:\n${r.out.slice(-500)}`); }
	const found = list.find((d) => d.name === databaseName);
	return found ? found.uuid : null;
}
let databaseId = findDatabase();
if (!databaseId) {
	console.log(`Creating the D1 database ${databaseName}…`);
	const r = run(['d1', 'create', databaseName]);
	if (r.code !== 0) fail(`could not create the D1 database:\n${r.out.slice(-800)}`);
	databaseId = findDatabase();
	if (!databaseId) fail('the D1 database was created but could not be found');
	summary.push(`Created the D1 database \`${databaseName}\`.`);
} else {
	summary.push(`Using the D1 database \`${databaseName}\`.`);
}

// 2. Was the intake paused? A deployment keeps it so, unless --resume
let paused = args.includes('--pause');
if (!args.includes('--pause') && !args.includes('--resume') && process.env.PLAYTEST_API_URL) {
	try {
		const health = await (await fetch(process.env.PLAYTEST_API_URL.replace(/\/+$/, '') + '/api/v1/health', { signal: AbortSignal.timeout(15000) })).json();
		paused = health.intake === 'paused';
		if (paused) console.log('The intake is paused: it stays paused (use --resume to reopen it).');
	} catch (error) { /* Not reachable yet: deploy open */ }
}
configure({ databaseId, paused, origins });

// 3. The tables, then the Worker, then its secret
let r = run(['d1', 'migrations', 'apply', databaseName, '--remote', '--config', generated]);
if (r.code !== 0) fail(`could not apply the database migrations:\n${r.out.slice(-800)}`);
r = run(['deploy', '--config', generated]);
if (r.code !== 0) {
	if (/workers\.dev subdomain/i.test(r.out)) fail('your account has no workers.dev subdomain yet: open dash.cloudflare.com > Workers & Pages once and choose one, then run this again');
	fail(`the deployment failed:\n${r.out.slice(-1200)}`);
}
const url = (r.out.match(/https:\/\/[A-Za-z0-9.-]+\.workers\.dev/) || [])[0];
r = run(['secret', 'put', 'IMPORT_TOKEN', '--config', generated], { input: process.env.PLAYTEST_IMPORT_TOKEN + '\n' });
if (r.code !== 0) fail(`the Worker is deployed, but its IMPORT_TOKEN secret could not be set:\n${r.out.slice(-600)}`);

// 4. Is it answering?
let health = null;
if (url) {
	for (let i = 0; i < 10 && !health; i++) {
		try {
			const response = await fetch(url + '/api/v1/health', { signal: AbortSignal.timeout(15000) });
			if (response.ok) health = await response.json();
		} catch (error) { /* Not yet */ }
		if (!health) await new Promise((resolve) => setTimeout(resolve, 3000));
	}
}
summary.push(url ? `Deployed to **${url}**.` : 'Deployed (the address was not found in wrangler\'s output: see Workers & Pages in the dashboard).');
summary.push(health ? `Health check: intake **${health.intake}**, import endpoints ${health.importEnabled ? 'on' : 'off'}.` : 'Health check: no answer yet (a new workers.dev address can take a minute).');
summary.push('', `Next: set the repository **variable** \`PLAYTEST_API_URL\` to \`${url || 'https://whitechapel-playtests.<your-subdomain>.workers.dev'}\`, then run **Deploy to GitHub Pages** (docs/automatic-playtest-collection.md#owner-setup).`);
console.log('\n' + summary.join('\n'));
if (process.env.GITHUB_STEP_SUMMARY) fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, '## Deploy playtest Worker\n\n' + summary.join('\n\n') + '\n');
